name: My Action

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: tranquilizer-/FRONTEND
      - name: Build project
        run: npm run build
        working-directory: tranquilizer-/FRONTEND
      - name: Deploy to server
        run: ssh user@server "cd /tranquilizer-/FRONTEND && npm run deploy"
